# Generated by Django 5.2.6 on 2025-10-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitentry",
            name="entry_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
