# Generated by Django 5.2.6 on 2025-12-04 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_habitentry_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
