# Generated by Django 5.2.6 on 2025-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_habit_last_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_date",
            field=models.DateTimeField(),
        ),
    ]
